// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUOroLbzF0lrznF552bH8ORefqmAiVNBg',
    appId: '1:68518491256:web:b509ec5e5c0b18998a298d',
    messagingSenderId: '68518491256',
    projectId: 'petsatthi',
    authDomain: 'petsatthi.firebaseapp.com',
    storageBucket: 'petsatthi.firebasestorage.app',
    measurementId: 'G-MXY6HFKXS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyv_A89xgBFJ0I0jxtgqr7e2WZzeLwOAM',
    appId: '1:68518491256:android:12a033e25b966c428a298d',
    messagingSenderId: '68518491256',
    projectId: 'petsatthi',
    storageBucket: 'petsatthi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQPVLNxTmF7Ip2F7UqCK9dD7H0_sodj-E',
    appId: '1:68518491256:ios:f8918e1380627d8c8a298d',
    messagingSenderId: '68518491256',
    projectId: 'petsatthi',
    storageBucket: 'petsatthi.firebasestorage.app',
    iosBundleId: 'com.example.petsaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQPVLNxTmF7Ip2F7UqCK9dD7H0_sodj-E',
    appId: '1:68518491256:ios:f8918e1380627d8c8a298d',
    messagingSenderId: '68518491256',
    projectId: 'petsatthi',
    storageBucket: 'petsatthi.firebasestorage.app',
    iosBundleId: 'com.example.petsaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUOroLbzF0lrznF552bH8ORefqmAiVNBg',
    appId: '1:68518491256:web:38919aea5f3cdaf48a298d',
    messagingSenderId: '68518491256',
    projectId: 'petsatthi',
    authDomain: 'petsatthi.firebaseapp.com',
    storageBucket: 'petsatthi.firebasestorage.app',
    measurementId: 'G-4HT0R1CRRQ',
  );

}